from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr

def story():
    
    vn.start()
    vn.label("beginning") 
    vn.show(a,"tired")
    vn.say(a,"Come on Ars... The last take wasn't so bad, was it?","a-01")
    vn.say(p,"It still sounds weird...","p-01")
    vn.say(a,"This is an entire Visual Novel Engine, Running in Minecraft, of course it'll be weird","a-02")
    vn.say(a,"No one has done this in 10 years! Give yourself some credit.","a-03")
    vn.say(p,"Yeah, I know, I know... But like...","p-02")
    vn.say(a,"You're getting tired Ars... Come on, let's end this...","a-04")
    vn.say(p,"No, let's do it, one more time...","p-03")    
    vn.say(a,".")
    vn.show(a,"sad")
    vn.say(a,"..")
    vn.say(a,"...")
    vn.show(a,"normal")
    vn.say(a,"Alright then...","a-05")
    vn.say(a,"But we'll do it my way","a-06")
    vn.say(p,"Huh?","p-04")
    vn.say(a,"We'll make this simple... Feature Listing","a-07")
    vn.say(p,"Just... Feature Listing?","p-05")
    vn.show(a,"happy")
    vn.say(a,"Yep! Let's keep it simple Ars, just like your programming philosophy~","a-08")
    vn.say(p,"Alright, let's do it your way...")
    vn.unlock_dialogue(["dsl","sdk","lua","grid","anarchy","old_mod"])
    vn.label("feature_listing")
    vn.next("feature_listing")
    vn.show(a,"normal")
    vn.say(a,"Alright then, which one should we show off next??","a-09")
    vn.label("page1")
    vn.choice({
        "sprite_system":"Sprite System",
        "compatibility" : "Mod Compatibility",
        "variables":"Variables",
        "page2":"Next One"
    })
    vn.label("page2")
    vn.choice({
        "day_night":"Day Night System",
        "idle_chat_system" : "Idle Chats",
        "background":"Background Change",
        "page3":"Next One"
    })
    vn.label("page3")
    vn.choice({
        "script_import":"Resource Pack System",
        "cupa":"Mob Talker System",
        "page1":"Return",
        "end":"That's all"
    })

    vn.label("cupa")
    vn.say(a,"Ah, this is Cupa's part isn't it?","a-10")
    vn.say(p,"Yeah, this is Cupa's part, I should go interact with her")
    vn.say(a,"Go ahead, I'll be waiting here then!","a-11")
    vn.finish()

    vn.label("script_import")
    vn.say(a,"Importing Scripts, right, this is rather important...","a-12")
    vn.say(a,"Importing script is very easy actually","a-13")
    vn.say(a,"This mob leverages the Minecraft Resource Pack system for Script And Asset Importing","a-14")
    vn.show_custom("asset","resource_pack",16,9,10,6,6,1)
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"In other words, you can load scripts the same way you load a Resource Pack","a-15")
    vn.remove("resource_pack")
    vn.show(a,"normal")
    vn.say(a,"I believe that's all  you need to know about installing a script, just load it like any other Resource Pack.","a-16")
    vn.jumpTo("feature_listing")

    vn.label("sprite_system")
    vn.say(a,"Alright, let's show off what we can do with Sprite Management!","a-17")
    vn.show_left(a,"happy")
    vn.say(a,"Here I am!","a-18")
    vn.show_right(a,"happy")
    vn.say(a,"Now I'm here","a-19")
    vn.show(a,"normal")
    vn.say(a,"Oh, and don't worry, we're not limited to only single character or a script. For example...","a-20")
    vn.show_custom(a,"happy",16,9,4,8,2,1)
    vn.show_custom("asset","modrinth",16,9,10,6,6,1)
    vn.say(a,"Tada! It's the Modrinth Page where you can download the mod!","a-21")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"As you can see, custom image and positioning is possible with this mod.","a-22")
    vn.show(a,"happy")
    vn.say(a,"Back to you Ars!","a-23")
    vn.remove("modrinth")
    vn.say(p,"Right, thank you Andr")
    vn.jumpTo("feature_listing")

    vn.label("compatibility")
    vn.show(a,"normal")
    vn.say(a,"Let's talk compatibility","a-24")
    vn.say(a,"Good news is, this mod requires no dependency","a-25")
    vn.say(a,"The Visual Novel Engine is written in pure java and...","a-26")
    vn.say(a,"Ars, do you want to...","a-27")
    vn.say(p,"No, I don't want to relive it, just... assume this thing runs on witch craft and it's compatible with anything.")
    vn.say(a,"Right... But yes, you shouldn't have any trouble with adding this mod to any modpack or even using the library into your own mod","a-28")
    vn.say(a,"That's how flexible this mod is~","a-29")
    vn.jumpTo("feature_listing")

    vn.label("variables")
    vn.say(a,"Hmm... What's a clever way to show off variable system...","a-30")
    vn.say(p,"Hmm...")
    vn.say(a,"Oh, I know~","a-31")
    vn.next("variable_finish")
    vn.finish()
    
    vn.label("variable_finish")
    vn.show(a,"tired")
    vn.say(a,"Ars... The last take wasn't so bad, was it?","a-01")
    vn.say(p,"Wait huh?")
    vn.show(a,"happy")
    vn.say(a,"Just kidding! As you can see, I can remember the last  thing we talked about even after you quit the dialogue screen or even close the game entirely.","a-32")
    vn.say(p,"Yeah, that's a clever way of showing it...")
    vn.jumpTo("feature_listing")

    vn.label("day_night")
    vn.say(a,"Hmm... This is straightforward...","a-33")
    vn.condNight([
        vn.say(a,"It's night time in game now~","a-34",nested =True)
    ])
    vn.condDay([
        vn.say(a,"It's day time in game now~","a-35",nested = True)
    ])
    vn.jumpTo("feature_listing")

    vn.label("idle_chat_system")
    vn.show(a,"happy")
    vn.say(a,"Oh I love this one! Thanks for adding this feature Ars!","a-36")
    vn.say(p,"Personally, I just hate it when a script is over and you can't do anything anymore")
    vn.say(p,"Feels more fun if script maker can add an infinite amount of random conversation into the script they're making")
    vn.say(a,"Yep! Anyway, let's trigger one~","a-37")
    vn.idle_chats()

    vn.label("background")
    vn.say(a,"This one's straightforward~","a-38")
    vn.background("void.png")
    vn.show(a,"happy")
    vn.say(a,"Ta Da! We've changed the background","a-39")
    vn.show(a,"normal")
    vn.say(a,"You can use this to create a CG Scene too","a-40")
    vn.say(a,"A full screen cutscene in your minecraft mod, fascinating isn't it?","a-41")
    vn.say(p,"Are we gonna do that bit?")
    vn.say(a,". . .","a-42")
    vn.show(a,"shy")
    vn.say(a,"Should we?","a-43")
    vn.say(p,"Youtube would probably bonk us... I dunno...")
    vn.say(a,"Mmmm... We do have to show off what this mod is capable of...","a-44")
    vn.say(a,"What's the worst that could happen?","a-45")
    vn.say(p,"Scorned by the algorithm???")
    vn.say(a,"I mean... This is a community... tool... thing, maybe it's fine if we do this? Like uhh... Fan Service???","a-46")
    vn.say(p,"Ahh... Now I regret not implementing proper animation feature. This would look good with animation!")
    vn.say(a,"That's what you're concerned about?","a-47")
    vn.say(p,"Actually, wait, back up, how about... we make this fanservice exclusive to the mod? Like, we'll put the resource pack here in the description and so people can explore more options.")
    vn.show(a,"normal")
    vn.say(a,"Oh! That's... perfect, actually. Yes, we should add that option in the menu...","a-48")
    vn.say(a,"Then if the player is curious, they can download the mod and trigger it themselves.","a-49")
    vn.say(p,"You hear that? Download the mod in Modrinth and the Resource Pack in the video's description! Then you can see the so-called Fanservice!")
    vn.say(a,"We can't promise it'll be good, but... It's just a demo after all~","a-50")
    vn.jumpTo("feature_listing")

    vn.label("fanservice")
    vn.show_custom("asset","black_screen",16,9,16,9,1,1)
    vn.remove(a)
    vn.background("andr_rain1.png")
    vn.play_music("rain_ambience")
    vn.say(a,"...","teleport")
    vn.say(a,"Ah... Player...","footstep")
    vn.say(a,"Ah... Player...","a-51")
    vn.say(a,"D-don't mind the clothes... It happens when I... get... wet...","a-52")
    vn.remove("black_screen")
    vn.say(a,"I... just want to apologize for last time...","a-53")
    vn.say(a,"I wanted to bring you a gift, but it suddenly start raining...","a-54")
    vn.say(a,"I... I only have a small piece of gravel left... That is, if you don't mind...","a-55")
    vn.say(a,"Next time, I... I promise I'll bring you something better...","a-56")
    vn.show_custom("asset","black_screen",16,9,16,9,1,1)
    vn.say(a,"You don't mind... don't you...?","a-57")
    vn.say(a,".")
    vn.say(a,"..")
    vn.say(a,"...")
    vn.clear_background()
    vn.remove("black_screen")
    vn.show(a,"scared")
    vn.say(a,"Gosh that was so embarrassing!","a-58")
    vn.say(a,"Aahhh... I can't believe I did that!!!","a-59")
    vn.say(p,"I mean, it wasn't that bad? Maybe???")
    vn.show(a,"shy")
    vn.say(a,"Let's just go back to the menu...","a-60")
    vn.say(p,"Ah, wait, wait...  That was AT2's art btw, just gotta mention that real quick")
    vn.say(a,"Yes, it was nice artwork, thank you... Can we go back please?","a-61")
    vn.say(p,"Right, let's go back")
    vn.jumpTo("feature_listing")

    vn.label("end")
    vn.say(a,"Alright, that's all of it for now","a-62")
    vn.say(a,"We might miss some of it, but...","a-63")
    vn.show(a,"happy")
    vn.say(a,"This very fully voiced demo is released in... The description below!","a-64")
    vn.say(a,"So go ahead and try!","a-65")
    vn.show(a,"normal")
    vn.say(a,"There's some scenes to be explored including the idle chats.","a-66")
    vn.say(a,"Any closing remark, Ars?","a-67")
    vn.say(p,"No, not really, thanks for your help Andr")
    vn.say(a,"You're welcome","a-68")
    vn.say(a,"We'll make a tutorial in the next part, take care now!","a-69")
    vn.finish()
    return vn.dialogueDict