from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr


def story():
    vn.start()
    vn.label("beginning") 
    vn.show(a,"tired")
    # vn.play_music("mice")
    vn.say(a,"Come on Ars... The last take wasn't so bad, was it?","a-01")
    vn.say(p,"It still sounds weird...","p-01")
    vn.say(a,"This is an entire Visual Novel Engine, Running in Minecraft, of course it'll be weird","a-02")
    vn.say(a,"No one has done this in 10 years! Give yourself some credit.","a-03")
    vn.say(p,"Yeah, I know, I know... But like...","p-02")
    vn.say(a,"You're getting tired Ars... Come on, let's end this...","a-04")
    vn.say(p,"No, let's do it, one more time...","p-03")    
    vn.say(a,".")
    vn.show(a,"sad")
    vn.say(a,"..")
    vn.say(a,"...")
    vn.show(a,"normal")
    vn.say(a,"Alright then...","a-05")
    vn.say(a,"But we'll do it my way","a-06")
    vn.say(p,"Huh?","p-04")
    vn.say(a,"We'll make this simple... Feature Listing","a-07")
    vn.say(p,"Just... Feature Listing?","p-05")
    vn.show(a,"happy")
    vn.say(a,"Yep! Let's keep it simple Ars, just like your programming philosophy~","a-08")
    vn.say(p,"Alright, let's do it your way...","p-06")
    vn.unlock_dialogue(["dsl","sdk","lua","grid","anarchy","old_mod"])
    vn.label("feature_listing")
    vn.next("feature_listing")
    vn.show(a,"normal")
    vn.say(a,"Alright then, which one should we show off next??","a-09")
    vn.label("page1")
    vn.choice({
        "sprite_system":"Sprite System",
        "compatibility" : "Mod Compatibility",
        "variables":"Variables",
        "page2":"Next One"
    })
    vn.label("page2")
    vn.choice({
        "day_night":"Day Night System",
        "idle_chat_system" : "Idle Chats",
        "background":"Background Change",
        "page3":"Next One"
    })
    vn.label("page3")
    vn.choice({
        "script_import":"Resource Pack System",
        "cupa":"Mob Talker System",
        "fanservice":"Fan Service",
        "end":"That's all"
    })

    vn.label("cupa")
    vn.say(a,"Ah, this is Cupa's part isn't it?","a-10")
    vn.say(p,"Yeah, this is Cupa's part, I should go interact with her","p-07")
    vn.say(a,"Go ahead, I'll be waiting here then!","a-11")
    vn.finish()

    vn.label("script_import")
    vn.say(a,"Importing Scripts, right, this is rather important...","a-12")
    vn.say(a,"Importing script is very easy actually","a-13")
    vn.say(a,"This mob leverages the Minecraft Resource Pack system for Script And Asset Importing","a-14")
    vn.show_custom("asset","resource_pack",16,9,10,6,6,1)
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"In other words, you can load scripts the same way you load a Resource Pack","a-15")
    vn.remove("resource_pack")
    vn.show(a,"normal")
    vn.say(a,"I believe that's all  you need to know about installing a script, just load it like any other Resource Pack.","a-16")
    vn.jumpTo("feature_listing")

    vn.label("sprite_system")
    vn.say(a,"Alright, let's show off what we can do with Sprite Management!","a-17")
    vn.show_left(a,"happy")
    vn.say(a,"Here I am!","a-18")
    vn.show_right(a,"happy")
    vn.say(a,"Now I'm here","a-19")
    vn.show(a,"normal")
    vn.say(a,"Oh, and don't worry, we're not limited to only single character or a script. For example...","a-20")
    vn.show_custom(a,"happy",16,9,4,8,2,1)
    vn.show_custom("asset","modrinth",16,9,10,6,6,1)
    vn.say(a,"Tada! It's the Modrinth Page where you can download the mod!","a-21")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"As you can see, custom image and positioning is possible with this mod.","a-22")
    vn.show(a,"happy")
    vn.say(a,"Back to you Ars!","a-23")
    vn.remove("asset","modrinth")
    vn.say(p,"Right, thank you Andr. Anyway, sprite positioning and whole other stuff will be explained later, during the uhh... Tutorials, after this video.","p-08")
    vn.jumpTo("feature_listing")

    vn.label("compatibility")
    vn.show(a,"normal")
    vn.say(a,"Let's talk compatibility","a-24")
    vn.say(a,"Good news is, this mod requires no dependency","a-25")
    vn.say(a,"The Visual Novel Engine is written in pure java and...","a-26")
    vn.say(a,"Ars, do you want to...","a-27")
    vn.say(p,"No, I don't want to relive it, just... assume this thing runs on witch craft and it's compatible with anything.","p-09")
    vn.say(a,"Right... But yes, you shouldn't have any trouble with adding this mod to any modpack or even using the library into your own mod","a-28")
    vn.say(a,"That's how flexible this mod is~","a-29")
    vn.jumpTo("feature_listing")

    vn.label("variables")
    vn.say(a,"Hmm... What's a clever way to show off variable system...","a-30")
    vn.say(p,"Hmm...","p-10")
    vn.say(a,"Oh, I know~","a-31")
    vn.next("variable_finish")
    vn.finish()
    
    vn.label("variable_finish")
    vn.show(a,"tired")
    vn.say(a,"Ars... The last take wasn't so bad, was it?","a-01")
    vn.say(p,"Wait huh?","p-11")
    vn.show(a,"happy")
    vn.say(a,"Just kidding! As you can see, I can remember the last  thing we talked about even after you quit the dialogue screen or even close the game entirely.","a-32")
    vn.say(p,"Yeah, that's a clever way of showing it...","p-12")
    vn.jumpTo("feature_listing")

    vn.label("day_night")
    vn.say(a,"Hmm... This is straightforward...","a-33")
    vn.condNight([
        vn.say(a,"It's night time in game now~","a-34",nested =True)
    ])
    vn.condDay([
        vn.say(a,"It's day time in game now~","a-35",nested = True)
    ])
    vn.jumpTo("feature_listing")

    vn.label("idle_chat_system")
    vn.show(a,"happy")
    vn.say(a,"Oh I love this one! Thanks for adding this feature Ars!","a-36")
    vn.say(p,"Personally, I just hate it when a script is over and you can't do anything anymore","p-13")
    vn.say(p,"Feels more fun if script maker can add an infinite amount of random conversation into the script they're making","p-14")
    vn.say(a,"Yep! Anyway, let's trigger one~","a-37")
    vn.show(a,"normal")
    vn.idle_chats()

    vn.label("background")
    vn.say(a,"This one's straightforward~","a-38")
    vn.background("void.png")
    vn.show(a,"happy")
    vn.say(a,"Ta Da! We've changed the background","a-39")
    vn.show(a,"normal")
    vn.say(a,"You can use this to create a CG Scene too","a-40")
    vn.say(a,"A full screen cutscene in your minecraft mod, fascinating isn't it?","a-41")
    vn.say(p,"Are we gonna do that bit?","p-15")
    vn.say(a,". . .","a-42")
    vn.show(a,"shy")
    vn.say(a,"Should we?","a-43")
    vn.say(p,"Youtube would probably bonk us... I dunno...","p-16")
    vn.say(a,"Mmmm... We do have to show off what this mod is capable of...","a-44")
    vn.say(a,"What's the worst that could happen?","a-45")
    vn.say(p,"Scorned by the algorithm???","p-17")
    vn.say(a,"I mean... This is a community... tool... thing, maybe it's fine if we do this? Like uhh... Fan Service???","a-46")
    vn.say(p,"Ahh... Now I regret not implementing proper animation feature. This would look good with animation!","p-18")
    vn.say(a,"That's what you're concerned about?","a-47")
    vn.say(p,"Actually, wait, back up, how about... we make this fanservice exclusive to the mod? Like, we'll put the resource pack here in the description and so people can explore more options.","p-19")
    vn.show(a,"normal")
    vn.say(a,"Oh! That's... perfect, actually. Yes, we should add that option in the menu...","a-48")
    vn.say(a,"Then if the player is curious, they can download the mod and trigger it themselves.","a-49")
    vn.say(p,"You hear that? Download the mod in Modrinth and the Resource Pack in the video's description! Then you can see the so-called Fanservice!","p-20")
    vn.say(a,"We can't promise it'll be good, but... It's just a demo after all~","a-50")
    vn.clear_background()
    vn.jumpTo("feature_listing")

    vn.label("fanservice")
    vn.stop_music()
    vn.play_music("rain_ambience")
    vn.show_custom("asset","andr_rain",16,9,16,9,1,1)
    vn.show_custom("asset","black_screen",16,9,16,9,1,1)
    vn.remove(a)
    vn.say("Narrator","It was midnight...")
    vn.say("Narrator","The soft patter of the rain awoke you from your sleep...")
    vn.say(a,"...","teleport")
    vn.say("Narrator","You can feel a presence appearing in your home...")
    vn.say(a,"Ah... Player...","a-51")
    vn.say("Narrator","It was a familiar voice...")
    vn.show_custom("asset","black_screen2",16,9,16,9,1,1)
    vn.remove("asset","black_screen")
    vn.say("Narrator","A figure shrouded in darkness stood before you...")
    vn.say(a,"D-don't mind the clothes... It happens when I... get... wet...","a-52")
    vn.show_custom("asset","black_screen3",16,9,16,9,1,1)
    vn.remove("asset","black_screen2")
    vn.say("Narrator","Your vision began to clear and you could make out your visitor...")
    vn.say("Narrator","An otherworldy beauty stood before you. Purple eyes gleamed in the dark, black clothing clung to her body, showing off patches of ivory skin...")
    vn.say(a,"I... just want to apologize for last time...","a-53")
    vn.say("Narrator","A light blush spread on the girl's face, she silently averted her gaze...")
    vn.remove("asset","black_screen3")
    vn.say(a,"I wanted to bring you a gift, but it suddenly start raining...","a-54")
    vn.say("Narrator","You noticed that she's clutching on a piece of gravel close to her chest, covering a glimpse of her soft skin...")
    vn.say(a,"I... I only have a small piece of gravel left... That is, if you don't mind...","a-55")
    vn.show_custom("asset","black_screen3",16,9,16,9,1,1)
    vn.say(a,"Next time, I... I promise I'll bring you something better...","a-56")
    vn.remove("asset","black_screen3")
    vn.show_custom("asset","black_screen2",16,9,16,9,1,1)
    vn.say(a,"You don't mind... don't you...?","a-57")
    vn.say(a,".")
    vn.say(a,"..")
    vn.say(a,"...")
    vn.show_custom("asset","black_screen",16,9,16,9,1,1)
    vn.remove("asset","black_screen2")
    vn.remove("asset","andr_rain")
    
    vn.remove("asset","black_screen")
    vn.show(a,"scared")
    # vn.play_music("mice")
    vn.stop_music()
    vn.say(a,"Gosh that was so embarrassing!","a-58")
    vn.say(a,"Aahhh... I can't believe I did that!!!","a-59")
    vn.say(p,"I mean, it wasn't that bad? Maybe???","p-21")
    vn.show(a,"shy")
    vn.say(a,"Let's just go back to the menu...","a-60")
    vn.say(p,"Ah, wait, wait...  That was AT2's art btw, just gotta mention that real quick","p-22")
    vn.say(a,"Yes, it was nice artwork, thank you... Can we go back please?","a-61")
    vn.say(p,"Right, let's go back","p-23")
    
    vn.jumpTo("feature_listing")

    vn.label("end")
    vn.say(a,"Alright, that's all of it for now","a-62")
    vn.say(a,"We might miss some of it, but...","a-63")
    vn.show(a,"happy")
    vn.say(a,"This very fully voiced demo is released in... The description below!","a-64")
    vn.say(a,"So go ahead and try!","a-65")
    vn.show(a,"normal")
    vn.say(a,"There's some scenes to be explored including the idle chats.","a-66")
    vn.say(a,"Any closing remark, Ars?","a-67")
    vn.say(p,"No, not really, thanks for your help Andr","p-24")
    vn.say(a,"You're welcome","a-68")
    vn.say(a,"We'll make a tutorial in the next part, take care now!","a-69")
    vn.say(p,"Don't forget to do all the things required to keep up with this content! All the buttons you need to press to tell the algorithm that you want to see the next part of this Mob Talker Script making Tutorial! Good bye then","p-25")
    vn.say(a,"...")
    vn.say(p,"...")
    vn.say(a,"Was that everything?","a-96")
    vn.say(p,"Yeah, I think...","p-75")
    vn.say(a,"Hmm...","a-97")
    vn.say(a,"So... why are we still here?","a-98")
    vn.say(p,"The Thumbnail!!!","p-76")
    vn.say(p,"Hold on, can you call Cupa?","p-77")
    vn.show_right(c,"normal")
    vn.say(c,"You rang?","c-30")
    vn.say(p,"We're making a thumbnail! We're gonna make something clickbaity!","p-78")
    vn.show_left(a,"tired")
    vn.say(a,"You're not thinking about anything weird... are you???","a-99")
    vn.say(c,"He's definitely thinking something weird!","c-31")
    vn.say(c,"Say, I remember Andr won the Tier List contest, so like...","c-32")
    vn.say(c,"Yknow~","c-33")
    vn.show_left(a,"shy")
    vn.say(a,"It was inconclusive...","a-100")
    vn.say(c,"I mean if you think about it, Ayumi's design is a bit... Yknow...","c-34")
    vn.say(c,"Anyway, lemme look for something~","c-35")
    vn.say(c,"Oooh~ I like this one","c-36")
    vn.show_custom("asset","andr_lying",16,9,16,9,1,1)
    vn.show(a,"scared")
    vn.say(a,"What are you doing?!?!","a-101")
    vn.say(a,"vn.remove(\"asset\",\"andr_lying\")")
    vn.remove("asset","andr_lying")
    vn.show_left(a,"shy")
    vn.say(a,"That was way too much, can't we have something normal?","a-102")
    vn.say(a,"Then again, why me? Why not you?","a-103")
    vn.show_custom("asset","cupa_valentine",16,9,16,9,1,1)
    vn.say(c,"Aww, that's actually cute~ What do you think Ars?","c-37")
    vn.say(p,"Doesn't feel clickbaity enough...","p-79")
    vn.remove("asset","cupa_valentine")
    vn.show_custom("asset","anniversary",16,9,16,9,1,1)
    vn.show(a,"happy")
    vn.say(a,"Oh that's lovely!","a-104")
    vn.show(p,"Yeah, But like... We need to communicate that this is a mod, yknow? Not an art thing...","p-80")
    vn.say(c,"Hmm... Let's try...","c-38")
    vn.remove("asset","anniversary")
    vn.say(c,"vn.show_custom(\"asset\",\"anniversary_full\",16,9,12,9,2,1)")
    vn.clear_background()
    vn.show_custom("asset","anniversary_full",16,9,12,9,3,1)
    vn.show_left(a,"normal")
    vn.show_right(c,"normal")
    vn.show_right(c,"happy")
    vn.say(c,"Tada! What do you think? Is it clickbaity enough???","c-39")
    vn.say(p,"Oh, I like that! Yeah~","p-81")
    vn.say(a,"Hmm... I suppose it's eye catching, but we do need to add some sort of title...","a-105")
    vn.show_right(c,"normal")
    vn.say(c,"Title huh??? Hmmm...","c-40")
    vn.say(c,"You wanna make one Ars?","c-41")
    vn.say(p,"Ugh... Feels like we're  drawing this out too much...","p-82")
    vn.show_left(a,"tired")
    vn.say(a,"If only you realize this 3 days ago...","a-106")
    vn.say(c,"What if... We use a screenshot of that Minecraft Movie?","c-42")
    vn.show_left(a,"normal")
    vn.say(p,"What?","p-83")
    vn.say(a,"What?","a-107")
    vn.background("minecraft_movie.png")
    vn.say(c,"Hey! It's all about algorithm, isn't it???","c-43")
    vn.say(a,"I mean...","a-108")
    vn.say(p,"Ahhh... You know what? I dunno if this is genius, or...","p-84")
    vn.say(c,"Come on, forget about the details!","c-44")
    vn.show_right(c,"happy")
    vn.say(c,"Put on your 'happy' sprite and smile for the thumbnail everyone!!!","c-45")
    vn.show_left(a,"happy")
    vn.say(c,"Put on your 'happy' sprite and smile for the thumbnail everyone!!!")
    vn.show_custom("asset","black_screen",16,9,16,9,1,1)
    vn.show_custom("asset","thanks",16,9,12,2,2,3)
    vn.say(p,"And thanks for watching","p-85")
    vn.say(p,"The boring stuff ahead, ahem, this thing was made in minecraft. Like all of em. I... I don't know how to edit videos, seriously, I... I have no idea how  to do any of that. This is a single take with an OBS, ahaha!","p-86")
    vn.say(p,"The artworks you saw were all made by AT2, I believe, I put his deviant art link in the description","p-87")
    vn.say(p,"The mod is licensed under LGPL and the sdk GPL, in other words... Yes, it's all Open Source and will always be Open Source","p-88")
    vn.say(p,"Fork it, extend it, expand it, pop off! Make something wonderful! That's all I'm asking!","p-89")
    vn.stop_music()
    vn.finish()
    return vn.dialogueDict