from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr

def story():
    
    vn.start()
    vn.show(c,"tired") 
    vn.say(c,"Wait, we're doing this again?","c-01")
    vn.say(p,"Uuuuh...")
    vn.show(c,"normal")
    vn.say(c,"Eh, fine, it's cool, the hard part is done, we're just doing an advert.","c-02")
    vn.say(c,"Anyway, time for my epic introduction! Again!","c-03")
    vn.show(c,"happy")
    vn.say(c,"Hello Internet! My name is Cupa and you are watching the rebirth of Mob Talker mod!!!","c-04")
    vn.show(c,"normal")
    vn.say(c,"How long has it been? Weeks? Months? Years? Decade???","c-05")
    vn.show(c,"happy")
    vn.say(c,"Yeah... It was a whole entire decade wasn't it!?","c-06")
    vn.show(c,"angry")
    vn.say(c,"Geez, can't believe this mod was abandoned for this long... Where have you been Ars?","c-07")
    vn.say(p,"I'm not the original developer, I just... decided I have too much time and decided to use it for remaking this mod.")
    vn.show(c,"happy")
    vn.say(c,"Eh, it can't be that that hard tho right?","c-08")
    vn.say(p,"I had to make a DSL")
    vn.say(c,"Sounds like a piece of cake!","c-09")
    vn.say(p,"And a Framework, and an SDK, and Java Intereoperability...")
    vn.say(c,"Yep! Another Modding Adventure!","c-10")
    vn.say(p,"It's nooootttt Oh My God It was So Hard!!!! AAAAAAAA-")
    vn.show(c,"normal")
    vn.say(c,"There, there, I don't know if it's actually hard or just skill issue, but... I am thankful that you went this far to make it.","c-11")
    vn.say(p,"Thank you... It was probably skill issue, but thanks anyway...")
    vn.show(c,"happy")
    vn.say(c,"Ahaha! Let's go back to the script!","c-12")
    vn.show(c, "normal")
    vn.say(c,"Ahem... right... Uhh... As you can see just now, the new mod uses Name Tag to tag a character.","c-13")
    vn.say(c,"My character as it appears in the Game doesn't come from this mod. This mod doesn't create any new mob nor is it dependent of any other mob","c-14")
    vn.say(c,"Basically, any entity that's named with the trigger word can trigger the mod.","c-15")
    vn.say(c,"The mod itself doesn't care about the type of entity it is.","c-16")
    vn.show_custom(c,"normal",16,9,4,8,2,1)
    vn.show_custom("asset","cupa1",16,9,4,8,5,1)
    vn.say(c,"For example, this is a Touhou Little Maid mod entity and it can trigger my (Cupa's) script because the name is Cupa","c-17")
    vn.show_custom("asset","cupa2",16,9,4,8,9,1)
    vn.say(c,"This, on the other hand, is a vanilla creeper with a CMM Resource  Pack on top of it. Though it looked a lot like me, it will not trigger because the name is 'Cupa-chan' not 'Cupa'","c-18")
    vn.show_custom("asset","cupa3",16,9,4,8,13,1)
    vn.say(c,"And this is a vanilla villager with the CMM Resource Pack on top of it, it will trigger because the name is Cupa","c-19")
    vn.say(p,"Ah, also, it's not case sensitive, you can name the mod cuPA and it'll still work!")
    vn.say(c,"True, true~ You can do that!","c-20")
    vn.say(p,"You can even name a chicken Cupa it'll still work! I mean, Vanilla Creepers would just blow up, don't you think?")
    vn.show_custom(c,"angry",16,9,4,8,2,1)
    vn.say(c,"Come on... there's a lot of mods out there you can install for extra immersion. Like look at that, the Touhou Little Maid model looks adorable, don't you think???","c-21")
    vn.show_custom(c,"normal",16,9,4,8,2,1)
    vn.say(c,"This mod is SUPER COMPATIBLE with any mods out there, so get creative! There's tons of  creeper girl out there, no need to settle with a chicken!","c-22")
    vn.say(p,"True that! This means that this mod isn't limited by the vanilla mobs like the old Mob Talker mod")
    vn.show_custom(c,"happy",16,9,4,8,2,1)
    vn.say(c,"Yep! You can have any characters in this mod, including other game, anime, or even movies!","c-23")
    vn.say(c,"We're... Should we do that bit?","c-24")
    vn.say(p,"Uhhh... What bit?")
    vn.show(c,"shy")
    vn.say(c,"You know...","c-25")
    vn.say(p,"Umm... I already uhh...")
    vn.show(c,"angry")
    vn.say(c,"You already did it with Andr???","c-26")
    vn.say(p,"Yeah... I can't find any good CG of you to work with so...")
    vn.show(c,"sad")
    vn.say(c,"Hmph... I knew it, you like her more than me...","c-27")
    vn.say(p,"Awww, come on, it's not like that! It's just uhh... Just so happens that Andr has something very cutsceneable and not TOO nsfw... get it?")
    vn.say(c,"Fine... I'll let it slide  this time","c-28")
    vn.say(c,"Now shoo, go away, Andr's waiting","c-29")
    vn.finish()
    return vn.dialogueDict