from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Player" 

def story():
    vn.start()
    vn.label("start") # This is a 'Label', it will be used by the jump and choice to know where to go

    vn.show(c,"tired") # show function will automatically create a path. "tired" is the sprite name, tired.png
    vn.say("???","Huh? W-Who's there??") # Say function (name, content). The namee takes either Character class or a regular string.
    vn.say("???","H-hello... Um... Do I... know you?")
    vn.choice({
        "comeinpeace": "I come in peace", # Format is (label : displayed text), this goes to the 'hi' label
        "creeperareyou": "Are you a creeper?"
    })

    vn.label("comeinpeace")
    vn.say(p,"Hey, it's okay, I'm not here to hurt you.")
    vn.say(p,"You can call me Player")
    vn.show(c,"sad")
    vn.say("???","Have we... met before?")
    vn.say(p, "No it's out first time meeting.")
    vn.say("???","Is that so?")
    vn.say(p,"And you? What's your name?")
    vn.show(c,"tired")
    vn.say("???","I don't know... I can't remember what happened to me... What's going on?")
    vn.show(c,"sad")
    vn.say("???","Everything is just a blur... Whenever I try to remember something... Anything, my head starts hurting...")
    vn.say(p,"(That's strange... A Creeper with Amnesia??? What happpened to her that caused her to forget everything?)")
    vn.show(c,"tired")
    vn.say("???","I'm sorry, I'd better get going...")
    vn.say(p,"Wait! Where are you going?")
    vn.show(c,"sad")
    vn.say("???","I...")
    vn.say("???","I don't know anymore...")
    vn.say(p,"You haven't tried staying in the village, have you? I don't think it's a good idea to go there.")
    vn.say("???","I know...")
    vn.say("???","The villagers were angry at me when I tried to stay there... I tried to tell them, but they wouldn't listen to me. They kept saying that I was going to blow up the village, and that I should leave.")
    vn.say("???","The villagers were so mean... They were yelling at me to leave and threw stuff at me.They treated me like an outsider, but that's not what I am, am I?")
    vn.show(c,"tired")
    vn.say(p,"Geez... I'm sorry to hear that...Of course the villagers wouldn't accept a Creeper like you...")
    vn.say("???","A creeper? But I haven't done creepy or weird to them, I think...")
    vn.say(p,"Hmm? No, not that kind of creeper.Creepers are these plant-based mobs that explode on other mobs, like you.")
    vn.say("???","I'm... a Creeper?")
    vn.show(c,"scared")
    vn.say(p,"What is it?")
    vn.show(c,"tired")
    vn.say("???","I remember... a woman in a black and white coat like mine. She seemed... familiar. Like I knew her somehow...")
    vn.show(c,"sad")
    vn.say(c,"She called me \"Cupa\"")
    vn.say(c,"That's my name... I think, Cupa")
    vn.say(p, "Cupa huh? That's a pretty name")
    vn.show(c,"shy")
    vn.say(c,"Really?  T-thank you...")
    vn.say(p,"Look, Cupa, if you don't have a place to stay, I can let you stay at my place.")
    vn.show(c,"tired")
    vn.say(c,"Are you... are you sure? wait... I-I can't, I could blow up your house or worse... I could")
    vn.say(p,"It's alright, I can fix the damage! So don't worry about it, you coming?")
    vn.show(c,"sad")
    vn.say(c,"Why...? Why are you going out of your way to help somebody like me?")
    vn.show(c,"tired")
    vn.say(c, "You said it yourself, I'm a Creeper! It's not just your house I could blow up! It's You!")
    vn.say(c,"I could KILL YOU, but you still want to help me?")
    vn.say(p,"...")
    vn.say(p,"Cupa...")
    vn.say(p,"I can't just leave you out here all by yourself.")
    vn.show(c,"sad")
    vn.say(c,"Huh???")
    vn.say(p,"I'm not gonna leave you out in this cruel world. What am I supposed to do if you were to get attacked and I didn't know? Sure, you're a Creeper. Maybe you could blow me up to smithereens.")
    vn.say(p,"Maybe I'm too trusting, but I believe that you wouldn't do that to me. Call me ignorant, call me whatever. It doesn't matter. All that matters is that you need help. So let me help you, Cupa.")
    vn.show(c,"tired")
    vn.say(c,"...")
    vn.show(c,"sad")
    vn.say(c,"...")
    vn.show(c,"normal")
    vn.say(c,"...")
    vn.show(c,"shy")
    vn.say(c,"...")
    vn.say(p,"So... you coming?")
    vn.say(c,"Y...yes... I'm coming")
    vn.addVar("aff",1)
    vn.modVar("day1a",True)
    vn.next("day1a")
    vn.finish()

    vn.label("creeperareyou")
    vn.say(p,"Are you a Creeper? Because you just blow me away.")
    vn.show(c,"angry")
    vn.say(c,"Eww, gross! Get away from me!")
    vn.show(p,"...")
    vn.show(p,"I guess this is what they call \"ending it with a bang\"...")
    vn.finish()

    vn.label("day1a")
    vn.say(p,"Here we are. Home sweet home.")
    vn.show(c,"happy")
    vn.say(c,"Wow! Your place looks so nice!")
    vn.say(p,"Make yourself at home. If you need anything, just let me know.")
    vn.say(c,"Thank you! Ahh, it's great to be somewhere nice and warm~")
    vn.show(c,"normal")
    vn.say(c,"...")
    vn.show(c,"sad")
    vn.say(c,"...?")
    vn.addVar("aff",1)
    vn.modVar("day1b",True)
    vn.next("day1b")
    vn.finish()

    vn.label("day1b")
    vn.show(c,"sad")
    vn.say(c,"...?")
    vn.say(p,"Yeah?")
    vn.say(p,"You look like you have something on your mind. Is something the matter?")
    vn.say(c,"Oh... Well...")
    vn.choice({
        "whathappened":"What happened?",
        "memories":"The woman in your memories"
    })

    vn.label("whathappened")
    vn.say(p,"You don't remember what exactly happened to you? How you lost your memories?")
    vn.show(c,"sad")
    vn.say(c,"No. I don't remember at all. It's frustrating... But...")
    vn.say(p,"What is it?")
    vn.show(c,"tired")
    vn.say(c,"I remember... When I woke up, I felt some sort of pain on the back of my head...")
    vn.say(p,"Let me see.")
    vn.say(c,"KYAH! W-What are you doing?!")
    vn.show(c,"sad")
    vn.say(p,"I'm not seeing anything. How long ago was this?")
    vn.say(c,"Uhh... A couple of weeks ago, I think?")
    vn.show(c,"shy")
    vn.say(c,"It doesn't hurt now. I was lucky enough to find some snow to ease the pain and patched myself up.")
    vn.say(p,"Well, if you were bleeding, that would've been a different story.")
    vn.say(c,"Yeah. Don't worry. I'm all right now, thanks.")
    vn.say(p,"You also said you saw a woman like you?")
    vn.show(c,"sad")
    vn.say(c,"Yeah. A woman with a black and white coat like mine. White hair, orange eyes, a black ribbon, and some blue clothing, I think?")
    vn.say(p,"A Creeper like you with a black coat and white hair? I haven't seen one like that... Is she a friend? Sister? Cousin? A mother, perhaps?")
    vn.show(c,"sad")
    vn.say(c,"She looked young, but I'm not sure. It's hard to describe, but I felt like I know her.")
    vn.show(c,"tired")
    vn.say(c,"Ugh, I hate not having to remember...")
    vn.say(p,"It's okay. Don't hurt yourself.")
    vn.addVar("aff",1)
    vn.modVar("day1c",True)
    vn.next("day1c")
    vn.finish()

    vn.label("memories")
    vn.say(p,"You said you saw a woman like you?")
    vn.show(c,"sad")
    vn.say(c,"Yeah. A woman with a black and white coat like mine. White hair, orange eyes, a black ribbon, and some blue clothing, I think?")
    vn.say(p,"A Creeper like you with a black coat and white hair? I haven't seen one like that... Is she a friend? Sister? Cousin? A mother, perhaps?")
    vn.say(c,"She looked young, but I'm not sure. It's hard to describe, but I felt like I know her. I wish I could remember more...")
    vn.say(p,"It's okay. Don't stress yourself out too much.")
    vn.show(c,"tired")
    vn.say(p,"You also said you don't remember what exactly happened to you? How you lost your memories?")
    vn.say(c,"No. I don't remember at all. It's frustrating... But...")
    vn.say(p,"What is it?")
    vn.show(c,"tired")
    vn.say(c,"I remember... When I woke up, I felt some sort of pain on the back of my head...")
    vn.say(p,"Let me see.")
    vn.say(c,"KYAH! W-What are you doing?!")
    vn.show(c,"sad")
    vn.say(p,"I'm not seeing anything. How long ago was this?")
    vn.say(c,"Uhh... A couple of weeks ago, I think?")
    vn.show(c,"shy")
    vn.say(c,"It doesn't hurt now. I was lucky enough to find some snow to ease the pain and patched myself up.")
    vn.say(p,"Well, if you were bleeding, that would've been a different story.")
    vn.say(c,"Yeah. Don't worry. I'm all right now, thanks.")
    vn.addVar("aff",1)
    vn.modVar("day1c",True)
    vn.next("day1c")
    vn.finish()

    vn.label("day1c")
    vn.show(c,"sad")
    vn.say(c,"Let's stop here. Hopefully, some of my memories will come back to me soon.")
    vn.say(p,"All right, then. Let's call it a day. Get yourself some rest, Cupa.")
    vn.show(c,"normal")
    vn.say(c,"I will.")
    vn.say(p,"See you tomorrow, Cupa.")
    vn.say(c,"See you.")
    vn.say(p,"Yeah?")
    vn.show(c,"happy")
    vn.say(c,"Thank you.")
    vn.unlock_dialogue(["pick_up","cupa_want_to_say"])
    vn.next("day1idle")
    vn.finish()

    vn.label("day1idle")
    vn.show(c,"normal")
    vn.say(c,"Oh... hi player...")
    
    vn.condNight([
        vn.say("system","End The Day???",True),
        vn.choice({
            "day1nightevent": "Yes",
            "idle_chat": "No"
        },True)
    ])
    
    vn.jumpTo("idle_chat")

    vn.label("day1nightevent")
    vn.show(c,"shy")
    vn.say(c,"So ummm... do you... have a spare bed?")
    vn.say(p, "What if I don't?")
    vn.show(c,"happy")
    vn.say(c,"I mean... I really don't mind sleeping on the floor, it beats sleeping outside and...")
    vn.say(p, "Uhh... yeah... I think I can craft a bed...")
    vn.show(c,"shy")
    vn.say(c,"R-really? That's very nice of you...")
    vn.next("day2")
    vn.finish()
    return vn.dialogueDict