from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Player" 

def story():
    vn.start()
    vn.label("day2")
    vn.show(c,"sad")
    vn.say(p,"Good morning, Cupa.")
    vn.show(c,"tired")
    vn.say(c,"Oh! Good morning, Player.")
    vn.show(c,"sad")
    vn.say(c,"I'm sorry, I must've been spacing out.")
    vn.say(p,"Is something the matter?")
    vn.say(c,"Well, it's just... A cat just passed by here. And I felt... scared.")
    vn.say(p,"Wait, really? You're scared of a cat?")
    vn.show(c,"angry")
    vn.say(c,"What, are you making fun of me? These cats can be very dangerous, you know. If you get caught with those claws, it's DEATH!")
    vn.say(p,"I think you're exaggerating a bit...")
    vn.show(c,"tired")
    vn.say(c,"I'm not! I remember I-- !")
    vn.say(p,"Cupa?")
    vn.show(c,"sad")
    vn.say(c,"I remember... There was a stray cat that approached me. I don't remember what happened after since I must've blacked out. I woke up and that same woman was taking care of me. Apparently, that stray cat gave me really bad gashes when I was unconscious and she drove it away. Ever since that incident, I was deathly afraid of cats... But that was when I was a kid. The scars have already healed now, but the trauma is still there...")
    vn.say(p,"Wow... I'm sorry to hear that, Cupa.")
    vn.show(c,"normal")
    vn.say(c,"It's okay.")
    vn.say(p,"But that woman... There's gotta be some sort of connection since you saw her again.")
    vn.show(c,"sad")
    vn.say(c,"You're right, but I still have no idea who she is...")
    vn.show(c,"angry")
    vn.say(c,"Hmm...")
    vn.show(c,"normal")
    vn.say(c,"Whatever it is, it means we're getting one step closer to the truth. Right?")
    vn.say(p,"Yeah, hopefully.")
    vn.show(c,"sad")
    vn.say(c,"Hey, Player. Can I ask you something?")
    vn.say(p,"Sure. What's up?")
    vn.say(c,"What's your story, anyway? How did you end up here?")
    vn.say(p,"To be honest, I don't know. It's sort of similar to your story though.")
    vn.show(c,"tired")
    vn.say(c,"Huh? What do you mean?")
    vn.show(p,"sad")
    vn.say(p,"Well, all I remember was waking up to a place like this. I only know my name and the kind of person I am. Since then, I've been doing what I can to survive. Building this house, cooking food, making a bed to sleep, trying to stay alive from the countless mobs that wanted me dead. Creepers, zombies, skeletons... It's been hell. Admittedly, it's a miracle that I'm still alive.")
    vn.say(c,"So you don't remember anything either? Like your parents or where you're from?")
    vn.show(p,"normal")
    vn.say(p,"Nope. Honestly, who knows? I guess all that matters to me right now is staying alive...")
    vn.show(c,"sad")
    vn.say(c,"Oh. I'm sorry, Player.")
    vn.show(p,"normal")
    vn.say(p,"It's all right. Let's just call it a day here.")
    vn.show(c,"normal")
    vn.say(c,"All right.")
    vn.say(p,"We should also stay inside. It looks like there's gonna be a storm later tonight.")
    vn.show(c,"sad")
    vn.say(c,"Oh, really? Okay. See you tomorrow, Player.")
    vn.say(p,"See you in the morning.")
    vn.next("day3")
    vn.finish()
    
    return vn.dialogueDict