from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr

def story():
    
    vn.start()
    vn.show(c,"scared") # show function will automatically create a path. "normal" is the sprite name, normal.png
    vn.say(c,"Dude! How are you not dead?")
    vn.say(c,"Andr looked like she's ready to murk you!!!")
    vn.say(p,"I dunno... Actually... You seem chill about this.")
    vn.show(c,"normal")
    vn.say(c,"Hey, I'm just glad the mod's revived, that's all! Anyway, time for that fancy mic thing tutorial, yea?")
    vn.say(p,"Yep, time for the fancy mic thing tutorial.")
    vn.show(c,"happy")
    vn.say(c,"Hello Internet! My name is Cupa and you are watching the rebirth of Mob Talker mod!!!")
    vn.show(c,"normal")
    vn.say(c,"How long has it been? Weeks? Months? Years? Decade???")
    vn.show(c,"happy")
    vn.say(c,"Yeah... It was a whole entire decade wasn't it!?")
    vn.show(c,"normal")
    vn.say(c,"Geez, can't believe this mod was abandoned for this long... Where have you been Ars?")
    vn.say(p,"I'm not the original developer, I just... decided I have too much time and decided to use it for remaking this mod.")
    vn.show(c,"happy")
    vn.say(c,"It's not that hard tho  right?")
    vn.say(p,"I had to make a DSL")
    vn.say(c,"Sounds like a piece of cake!")
    vn.say(p,"And a Framework, and an SDK, and Java Intereoperability...")
    vn.say(c,"Yep! Another Modding Adventure!")
    vn.say(p,"It's nooootttt Oh My God It was So Hard!!!! AAAAAAAA-")
    vn.show(c,"normal")
    vn.say(c,"There, there, I don't know if it's actually hard or just skill issue, but... I am thankful that you went this far to make it.")
    vn.say(p,"Thank you, it was probably skill issue, but thanks anyway...")
    vn.show(c,"happy")
    vn.say(c,"Ahaha! Let's go back to the script!")
    vn.show(c, "normal")
    vn.say(c,"Ahem... right... Uhh... As you can see just now, the new mod uses Name Tag to tag a character.")
    vn.say(c,"My character as it appears in the Game doesn't come from this mod. This mod doesn't create any new mob nor is it dependent of any other mob")
    vn.say(c,"Basically, any entity that's named with the trigger word can trigger the mod.")
    vn.say(c,"The mod itself doesn't care about the type of entity it is.")
    vn.show_custom(c,"normal",16,9,4,8,2,1)
    vn.show_custom("asset","cupa1",16,9,4,8,5,1)
    vn.say(c,"For example, this is a Touhou Little Maid mod entity and it can trigger my (Cupa's) script because the name is Cupa")
    vn.show_custom("asset","cupa2",16,9,4,8,9,1)
    vn.say(c,"This, on the other hand, is a vanilla creeper with a CMM Resource  Pack on top of it. Though it looked a lot like me, it will not trigger because the name is 'Cupa-chan' not 'Cupa'")
    vn.show_custom("asset","cupa3",16,9,4,8,13,1)
    vn.say(c,"And this is a vanilla villager with the CMM Resource Pack on top of it, it will trigger because the name is Cupa")
    vn.say(p,"Ah, also, it's not case sensitive, you can name the mod cuPA and it'll still work!")
    vn.say(c,"True, true~ You can do that!")
    vn.say(p,"You can even name a chicken Cupa it'll still work! I mean, Vanilla Creepers would just blow up, don't you think?")
    vn.show_custom(c,"angry",16,9,4,8,2,1)
    vn.say(c,"Come on... there's a lot of mods out there you can install for extra immersion. Like look at that, the Touhou Little Maid model looks adorable, don't you think???")
    vn.show_custom(c,"normal",16,9,4,8,2,1)
    vn.say(c,"This mod is SUPER COMPATIBLE with any mods out there, so get creative! There's tons of  creeper girl out there, no need to settle with a chicken!")
    vn.say(p,"True that! This means that this mod isn't limited by the vanilla mobs like the old Mob Talker mod")
    vn.show_custom(c,"happy",16,9,4,8,2,1)
    vn.say(c,"Yep! You can have any characters in this mod, including other game, anime, or even movies!")
    vn.show(c,"normal")
    vn.remove("asset","cupa1")
    vn.remove("asset","cupa2")
    vn.remove("asset","cupa3")
    vn.say(c,"Psst, ready?")
    vn.say(p,"Yeah")
    vn.show(c,"happy")
    vn.say("Cupa and Ars","Imagine the possibilities!")
    vn.say(c,"...")
    vn.say(p,"...")
    vn.show(c,"normal")
    vn.say(c,"Did we nail it?")
    vn.choice({
        "nailed_it":"Nailed It!",
        "nailnt":"No..."
    })

    vn.label("nailed_it")
    vn.say(c,"Aww, Hell yeah!",True)
    vn.say(c,"Let's goooo!!!")
    vn.jumpTo("finish_nailing")

    vn.label("nailnt")
    vn.say(c,"Ah, dammit..")
    vn.say(c,"I'd say we try again but Andr looks like she's  gonna teleport us to the Void any second now, so...")
    vn.say(c,"Let's just keep going")
    vn.say(p,"Yeah, true, true!")
    vn.jumpTo("finish_nailing")

    vn.label("finish_nailing")
    vn.show(c,"normal")
    vn.say(c,"Anyway I think that's all I need to do...")
    vn.show(c,"happy")
    vn.say(c,"Thanks for listening!")
    vn.say(c,"Good luck to you Ars!!!")
    vn.finish()
    return vn.dialogueDict