from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr

def story():
    
    vn.start()
    vn.label("beginning") 
    vn.show(a,"tired") 
    vn.play_music("mountain_king")
    vn.say(a,"Oh my god... Really? Again? Look, the last one works well, just use that!","a-01")
    vn.say(p,"Whoa! Hey, Andr, OBS is up, you're on camera. Come on, put on a smile!")
    vn.show(a,"angry")
    vn.say(a,"I don't care! This is the 24th Take! And we haven't even begin making a tutorial! Just your stupid introduction!!!","a-02")
    vn.show(a,"tired")
    vn.say(p,"Look, you know I suck at Video Editing, I have to do this in one take!")
    vn.show(a,"angry")
    vn.say(a,"Screw that! You're just being stupid! Just skip the intro and make a tutorial, that's all everyone's asking!","a-03")
    vn.show(a,"tired")
    vn.say(p,"Last one, I promise! It's just... The Audio's scuffed and like, everything's so static and...")
    vn.show(a,"angry")
    vn.say(a,"This is a Visual Novel Engine running in MINECRAFT!!! What? You gonna delay the tutorial again until you add Live2D Support? Is that it?!","a-04")
    vn.show(a,"tired")
    vn.say(a,"right... the viewers...","a-05")
    vn.say(a,"Sorry, it's been a long day","a-06")
    vn.show(a,"normal")
    vn.say(a,"*sigh* Let's... start over...","a-07")
    vn.say(a,"Hello, it's been a while","a-08")
    vn.say(a,"Before you ask, yes, everything you see is rendered in real time in Minecraft","a-09")
    vn.say(p,"And the voice too! HA! Fully Voice VN in Minecraft! TAKE THAT!!!")
    vn.show(a,"tired")
    vn.say(a,"I... I... Am I gonna be the one doing this or...","a-10")
    vn.say(p,"Ah, sorry, sorry! Back to you Andr")
    vn.show(a,"normal")
    vn.say(a,"Regardless, this is the first part tutorial of the Mob Talker mod for 1.20.1","a-11")
    vn.say(a,"All the link's in the description, so let's get right to it.","a-12")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.show_custom("asset","modrinth",16,9,10,6,6,1)
    vn.say(a,"This... is the Mob Talker Framework...","a-13")
    vn.say(p,"There's a Curseforge Page btw!")
    vn.show_custom(a,"tired",16,9,4,8,2,1)
    vn.say(a,"...let's go somewhere nicer...","a-14")
    vn.background("void")
    vn.say(p,"This feels like a subtle threat...")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"This is a half a month project... It's still a bit rough around the edges, but as you can see, it's functional","a-15")
    vn.say(p,"Ha! Only half a month! Take that!!!")
    vn.show_custom(a,"angry",16,9,4,8,2,1)
    vn.say(a,"Ars, another word out of your mouth and I swear...","a-16")
    vn.say(p,"Sorry")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"It has almost all of the functionality of the old mod and more. It supports branching dialogue, choices, conditional, and other essential features of a Visual Novel.","a-17")
    vn.say(p,"I say it's a bloody upgrade from the old mod!")
    vn.show_custom(a,"angry",16,9,4,8,2,1)
    vn.say(a,".")
    vn.say(a,"..")
    vn.say(a,"...")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"Ahem... This mod doesn't have AI system like the Old Mob Talker mod because the dev can't understand how Minecraft Entity AI works. Ars is too lazy to implement proper time system and decided to instead FORCE Script Maker to make use of Day/Night awareness system for a sense of progression and prevent players from speedrunning.","a-18")
    vn.say(p,"Wait! Wait! Wait!")
    vn.say(a,"The system has no proper Database management, doesn't even use Json to put down script. It literally attaches updated variables at the end of the script's Json and copy it into the saves folder.","a-19")
    vn.say(p,"Oi, oi, Andr, it's a feature it'll make it easier to...")
    vn.say(a,"And the Dev is too lazy to create a Mob Entity and decided to use 'Name Tag' of all things to tag mob with script. Didn't even bother creating the Crafting Recipe for the Very Item Required to play the mod.","a-20")
    vn.say(p,"I will get right to it AFTER I finish this video!!!")
    vn.say(a,"Not to mention that the SDK itself, doesn't come with a proper build  files, no dependency, barely there documentation, and looked like it was an experiment on Anarchy Driven Development","a-21")
    vn.say(p,"I, Um, wait, ahh... HMM...")
    vn.show_custom(a,"tired",16,9,4,8,2,1)
    vn.say(a,"are you gonna shut up?","a-22")
    vn.say(p,"Yeah, sorry, continue then")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"Ahem... Moving on... Just like the old mod, this mod doesn't come with a script. You have to  look for scripts yourself. Depending on when you watch this video, you might already have a script you want to play.","a-23")
    vn.say(a,"But if not, there's a Discord Server in the description of thiis video where Ars planned to have people share scripts and such.","a-24")
    vn.show_custom(a,"happy",16,9,4,8,2,1)
    vn.say(a,"The discord server is deserted, by the way, nobody cares enough about him.","a-25")
    vn.say(p,"Ugh... you just  have to say it")
    vn.say(a,"Don't get me wrong though! The Mob Talker community is still thriving, it's just the server that's deserted. Hell, there's more bots than humans in that server","a-26")
    vn.say(p,"It was a place where I test Discord Bots okay?")
    vn.say(a,"Personally I think it's just skill issue on his part. He's really bad at the bare minimum of content creation. No wonder nobody even know he exists! ","a-27")
    vn.say(p,"Ugh... Look, sorry, okay?")
    vn.show(a,"tired")
    vn.say(a,"...","a-28")
    vn.say(p,"Wait... I just realized, it's possible  to automate creating voice lines... WAIT!")
    vn.show(a,"angry")
    vn.say(a,"And there you go again... Goodness sake, this is why you never made it as a content creator! Your mind is all over the place, stay focused!","a-29")
    vn.remove("modrinth")
    vn.say(p,"Ouch?")
    vn.say(a,"Look, visit the server for Scripts! If there's any!","a-30")
    vn.say(p,"Hey, be nice with the viewers!")
    vn.show(a,"tired")
    vn.say(a,"*sigh*","a31")
    vn.say(a,"*sigh* Sorry, lemme catch my breath, it's been a long day...","a-32")
    vn.say(p,"Take your time~")
    vn.show(a,"normal")
    vn.say(a,"Installing script is easy. It's the same as installing a resourcepack","a-33")
    vn.say(a,"No like, literally...","a-34")
    vn.say(a,"This mod leverages Minecraft's Resource Pack system for Script Import","a-35")
    vn.say(a,"Alright, your turn then... I need to clear my head for a bit...","a-36")
    vn.next("resouce_pack_install")
    vn.finish()

    vn.label("resouce_pack_install")
    vn.show(a,"normal")
    vn.say(a,"Welcome back, wasn't so hard now, wasn't it? So yes, installing a script is only a matter of dragging the zip file into the resource pack folder.","a-37")
    vn.say(a,"Now let's take a closer look at the Resource Pack page...","a-38")
    vn.show_custom("asset","resource_pack",16,9,10,6,6,1)
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"Inside the Resource Pack is everything the Script needs to function. This includes character art, sprite, sounds if any, and more. Basically, the mod doesn't provide any assets, that's all from the Script Maker","a-39")
    vn.say(a,"If the Script Maker made it properly there will be a line called Trigger Word... It's... Cupa's turn, actually, shoo, go talk to her.","a-40")
    vn.say(p,"Alright, geez...")
    vn.next("intro_credit")
    vn.finish()

    vn.label("intro_credit")
    vn.show(a,"normal")
    vn.say(a,"Welcome back","a-41")
    vn.say(p,"Hello~")
    vn.say(a,"And that's everything you need to know about installing this mod.","a-42")
    vn.say(a,"To recap, all you have to do install the mod like any other, install the script like resource pack, and name a mob with the Trigger Word.","a-43")
    vn.show(a,"happy")
    vn.say(a,"Thanks for watching, the next videos  will talk about how to make scripts!","a-44")
    vn.show(a,"tired")
    vn.say(a,"If... Ars didn't make another retake...","a-45")
    vn.show(a,"normal")
    vn.say(a,"...")
    vn.say(a,"Are we done?","a-46")
    vn.say(p,"Should we do the credits?")
    vn.say(a,"Oh right! Ahem, the credits screen","a-47")
    vn.say(a,"My character sprite was built by AT2, the original artist of the Mob Talker mod","a-48")
    vn.say(a,"My 'voice' that you are hearing is an AI Model called “Shigure Tokina (CV: Marukoro)” created by “Administrator: Bindume”","a-49")
    vn.say(p,"Don't worry! This Project is Non Commercial and Open Source, I am not gatekeeping any content behind a paywall!")
    vn.say(p,"Well, Script maker can gatekeep content tho! That part's beyond me. But the engine, SDK, Mod, it's free baby! Just fork it! Make a better one! See if I care, ahaha!")
    vn.show(a,"happy")
    vn.say(a,"That's right! The Mob Talker SDK is licensed under GPL-3 and the Mob Talker Mod is licensed under LGPL 2.1 as per Mojang's Terms","a-50")
    vn.show(a,"normal")
    vn.say(a,"I believe that's all the credits for now. Should I credit Microsoft for stea-I mean, acquiring Minecraft?","a-51")
    vn.say(p,"...")
    vn.show(a,"tired")
    vn.say(a,"...")
    vn.show(a,"happy")
    vn.say("Andr and Ars","Thank you for watching!!!","a-52")
    vn.say(p,"See you in the next video!")
    vn.say(a,"Don't forget to subscribe!","a-53")
    vn.say(p,"Hit the like, bell, you know  the deal!")

    vn.next("sdk_installation")
    vn.finish()
    return vn.dialogueDict