from core.modules import VisualNovelModule
# This is the Example Script, obviously~

from characters import Cupa,Andr # Import characters you've defined in characters.py
vn = VisualNovelModule()
c = Cupa 
p = "Ars" 
a = Andr

def story():
    
    vn.start()
    vn.label("beginning") # This is a 'Label', it will be used by the jump and choice to know where to go
    vn.show(a,"tired") # show function will automatically create a path. "normal" is the sprite name, normal.png
    vn.say(a,"I swear by the abyss if we have to do another take...")
    vn.say(p,"Whoa! Hey, Andr, OBS is up, you're on camera")
    vn.show(a,"angry")
    vn.say(a,"I don't care! It's been 15 takes and I'm so, so tired of this...")
    vn.say(p,"Look, you know I suck at Video Editing, I have to do this in one take!")
    vn.say(a,"It's not about making a good video, it's about you being a bloody perfectionist! You never made a video in your entire life, stop putting up a standard about making 'Good Video'. Just make a tutorial, that's all everyone's asking!")
    vn.show(a,"tired")
    vn.say(p,"Last one, I promise! It'll be different this time I added a new feature that'll make things easier!")
    vn.say(a,"Ugh... Fine...")
    vn.say(a,"It's on... Right...")
    vn.say(a,"Sorry everyone, this is our 15th take... Because SOMEONE is a bloody perfectionist...")
    vn.show(a,"normal")
    vn.say(a,"*sigh* Let's... start over...")
    vn.say(a,"Hello, it's been a while")
    vn.say(a,"Pleasure to meet you again player. And before you ask, yes, everything you see is rendered in real time in Minecraft")
    vn.say(p,"And the voice too! HA! Fully Voice VN in Minecraft! TAKE THAT!!!")
    vn.show(a,"tired")
    vn.say(a,"Ars are you gonna do it or me?")
    vn.say(p,"Ah, sorry, sorry! Back to you Andr")
    vn.show(a,"normal")
    vn.say(a,"Regardless, this is the first part tutorial of the Mob Talker mod for 1.20.1")
    vn.say(a,"All the link's in the description, so let's get right to it.")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.show_custom("asset","modrinth",16,9,10,6,6,1)
    vn.say(a,"This... is the Mob Talker Framework...")
    vn.say(p,"There's a Curseforge Page btw!")
    vn.show_custom(a,"tired",16,9,4,8,2,1)
    vn.say(a,"...")
    vn.say(p,"Right, sorry")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"This is a half a month project... It's still a bit rough around the edges, but as you can see, it's functional")
    vn.say(a,"It has almost all of the functionality of the old mod and more. It supports branching dialogue, choices, conditional, and other essential features of a Visual Novel.")
    vn.say(p,"I say it's a bloody upgrade!!!")
    vn.show_custom(a,"angry",16,9,4,8,2,1)
    vn.say(a,"Alright,that's it")
    vn.say(a,"This mod doesn't have AI system because the dev can't understand how Minecraft AI works. Ars is too lazy to implement proper time system and decided to instead force Script Maker to make use of Day/Night awareness system for a sense of progression.")
    vn.say(p,"Wait! Wait! Wait!")
    vn.say(a,"The system has no proper Database management, doesn't even use Json to put down script. It literally attaches updated variables at the end of the script's Json and copy it into the saves folder.")
    vn.say(p,"Oi, oi, Cupa, it's a feature it'll make it easier to...")
    vn.say(a,"And the Dev is too lazy to create a Mob Entity and decided to use 'Name Tag' of all things to tag mob with script. Didn't even bother creating the Crafting Recipe for the Very Item Required to play the mod.")
    vn.say(p,"I will get right to it AFTER I finish this video!!!")
    vn.show_custom(a,"tired",16,9,4,8,2,1)
    vn.say(a,"...")
    vn.say(p,"Sorry, you can continue")
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"Just like the old mod, this mod doesn't come with a script. You have to  look for scripts yourself. Depending on when you watch this video, you might already have a script you want to play.")
    vn.say(a,"But if not, there's a Discord Server in the description of thiis video where Ars planned to have people share scripts and such.")
    vn.show_custom(a,"happy",16,9,4,8,2,1)
    vn.say(a,"It's deserted by the way! No activities in the slightest!!!")
    vn.say(p,"Ugh... you just  have to say it")
    vn.say(a,"There are more bots in the server than humans!")
    vn.say(p,"It was a place where I test Discord Bots okay?")
    vn.remove("modrinth")
    vn.show(a,"normal")
    vn.say(a,"Well, I do hope that people would discover that place... Ars here just want to start playing VN in Minecraft.")
    vn.say(a,"Anyway, next up is script installation")
    vn.say(a,"It's quite easy, actually")
    vn.say(a,"It's the same as installing a resourcepack")
    vn.say(a,"No like, literally...")
    vn.say(a,"All script, character sprite, and any other required assets are shipped using a Resource Pack")
    vn.show(a,"normal")
    vn.say(a,"Alright Ars, your turn")
    vn.next("resouce_pack_install")
    vn.finish()

    vn.label("resouce_pack_install")
    vn.show(a,"normal")
    vn.say(a,"Welcome back, wasn't so hard now, wasn't it?")
    vn.say(p,"Very easy! Barely an inconvenience")
    vn.show(a,"normal")
    vn.say(a,"That's it, that's the entire installation")
    vn.say(a,"Now let's take a closer look at the Resource Pack page...")
    vn.show_custom("asset","resource_pack",16,9,10,6,6,1)
    vn.show_custom(a,"normal",16,9,4,8,2,1)
    vn.say(a,"Inside the Resource Pack is everything the Script needs to function. This includes character art, sprite, sounds if any, and more. Basically, the mod doesn't provide any assets, that's all from the Script Maker")
    vn.say(a,"If the Script Maker made it properly there will be a line called Trigger Word... It's... Cupa's turn, actually, shoo, go talk to her.")
    vn.say(p,"Alright, geez...")
    vn.next("intro_credit")
    vn.finish()

    vn.label("intro_credit")
    vn.show(a,"normal")
    vn.say(a,"Welcome back")
    vn.say(p,"Hello~")
    vn.say(a,"And that's everything you need to know about installing this mod")
    vn.say(a,"To recap, all you have to do install the mod like any other, install the script like resource pack, and name a mob with the Trigger Word.")
    vn.show(a,"happy")
    vn.say(a,"Thanks for watching, the next videos  will talk about how to make scripts!")
    vn.say(a,"Looking forward to what you guys can create with this mod!")
    vn.show(a,"normal")
    vn.say(a,"...")
    vn.say(a,"Are we done?")
    vn.say(p,"Should we do the credits?")
    vn.say(a,"Oh right! Ahem, the credits screen")
    vn.say(a,"My character sprite was built by AT2, the original artist of the Mob Talker mod")
    vn.say(a,"My 'voice' that you are hearing is an AI Model called “Shigure Tokina (CV: Marukoro)” created by “Administrator: Bindume”")
    vn.say(p,"Don't worry! This Project is Non Commercial and Open Source, I am not gatekeeping any content behind a paywall!")
    vn.show(a,"happy")
    vn.say(a,"That's right! The Mob Talker SDK is licensed under GPL-3 and the Mob Talker Mod is licensed under LGPL 2.1 as per Mojang's Terms")
    vn.show(a,"normal")
    vn.say(a,"I believe that's all the credits for now. Should I credit Microsoft for stea-I mean, acquiring Minecraft?")
    vn.say(p,"...")
    vn.show(a,"tired")
    vn.say(a,"...")
    vn.show(a,"happy")
    vn.say("Andr and Ars","Thank you for watching!!!")
    vn.say(p,"See you in the next video!")
    vn.say(a,"Don't forget to subscribe!")

    vn.next("sdk_installation")
    vn.finish()
    return vn.dialogueDict